name: Update ouidb json file every night

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: run ouidb-to-json-publisher
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          EMAIL: ${{ secrets.EMAIL }}
        run: >
          docker run --name ouidb-to-json-publisher --rm
          --env "REPO_USERNAME=${MY_GITHUB_TOKEN}"
          --env "REPO_URL=https://github.com/jfisbein/ouidb-json"
          --env "GIT_AUTHOR_NAME=Joan Fisbein"
          --env "GIT_AUTHOR_EMAIL=${EMAIL}"
          jfisbein/ouidb-to-json-publisher:edge
