name: Update ouidb json file every night

on:
  schedule:
    - cron: "0 6 * * *"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: run ouidb-to-json-publisher
        run: >
          docker run --name ouidb-to-json-publisher --rm
          --env "REPO_USERNAME=${{ secrets.MY_GITHUB_TOKEN }}"
          --env "REPO_URL=https://github.com/jfisbein/ouidb-json"
          --env "GIT_AUTHOR_NAME=Joan Fisbein"
          --env "GIT_AUTHOR_EMAIL=${{ secrets.EMAIL }}"
          jfisbein/ouidb-to-json-publisher
